### ISSUE TITLE
Could not open comm

### ISSUE THREAD

**Issue by bluesmoon** [JuliaLang/Interact.jl#58]
I tried the example code:

`s = slider(0:.1:1, label="Slider X:")`

and there was no output, but I got the following error instead in my JavaScript console:

```
WrappedError
error_stack: Array[2]
0: Error: Class WidgetModel not found in registry
1: Error: Could not open comm
message: "Could not open comm"
stack: "Error: Could not open comm↵    at new Error (native)↵    at Error.WrappedError (https://localhost/static/base/js/utils.js:696:25)↵    at https://localhost/static/base/js/utils.js:775:33"
__proto__: Object
(anonymous function)	@	utils.js:776
```

**Comment by shashi** [comment]
If you are using IPython 3.0, you need to check out Interact on master. Have you tried this yet?

**Comment by bluesmoon** [comment]
thanks, will do

**Comment by bluesmoon** [comment]
that fixed it.
